package com.sign.record.dto;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hours_record.id
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hours_record.date
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hours_record.fixedhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    private String fixedhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hours_record.actualhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    private String actualhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hours_record.type
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    private Integer type;
    
    private Date starttime;
    
    private Date endtime;
    
    private int week;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hours_record.id
     *
     * @return the value of t_hours_record.id
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hours_record.id
     *
     * @param id the value for t_hours_record.id
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hours_record.date
     *
     * @return the value of t_hours_record.date
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hours_record.date
     *
     * @param date the value for t_hours_record.date
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hours_record.fixedhours
     *
     * @return the value of t_hours_record.fixedhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public String getFixedhours() {
        return fixedhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hours_record.fixedhours
     *
     * @param fixedhours the value for t_hours_record.fixedhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public void setFixedhours(String fixedhours) {
        this.fixedhours = fixedhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hours_record.actualhours
     *
     * @return the value of t_hours_record.actualhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public String getActualhours() {
        return actualhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hours_record.actualhours
     *
     * @param actualhours the value for t_hours_record.actualhours
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public void setActualhours(String actualhours) {
        this.actualhours = actualhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hours_record.type
     *
     * @return the value of t_hours_record.type
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hours_record.type
     *
     * @param type the value for t_hours_record.type
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

	public Date getStarttime() {
		return starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public int getWeek() {
		return week;
	}

	public void setWeek(int week) {
		this.week = week;
	}
    
    
    
}